### ISSUE TITLE
Add Croatian event on OpenDataDay wiki

### ISSUE THREAD

**Issue by schlos** [codeforcroatia/codeacross#25]
edit wiki and add link to Croatian official event webpage:
http://wiki.opendataday.org/2016/City_Events

official webpage:
http://codeacross.codeforcroatia.org

**Comment by schlos** [comment]
@rodik sorry, dodao sam na tebe slucajno, mislio sam da si mi rekao na chatu da si to napravio (ali bila je mapa). mozes li i wiki editirati da na popisu za Hr prikazuje nas event, grad i link na event?

Wiki: http://wiki.opendataday.org/2016/City_Events

Sluzbena stranica biti ce codeacross.codeforcroatia.org

**Comment by rodik** [comment]
Je, pogledao sam već to. Sredim kroz par sati.
